import { Event, User, Notification } from '../types';
import { mockVenues } from './mock-venues';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'alex@example.com',
    name: 'Alex Novák',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    bio: 'Passionate football organizer',
    karmaPoints: 42,
    skillLevels: { football: 'intermediate', basketball: 'beginner' },
    notificationPreferences: { football: true, basketball: true },
    preferredCurrency: 'EUR',
    location: 'Prague, Czech Republic',
    revTag: 'alexnovak',
    bankAccount: '123456789/0100',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    email: 'ben@example.com',
    name: 'Ben König',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    bio: 'Weekend warrior',
    karmaPoints: 28,
    skillLevels: { football: 'advanced', volleyball: 'intermediate' },
    notificationPreferences: { football: true, volleyball: false },
    preferredCurrency: 'EUR',
    location: 'Vienna, Austria',
    revTag: 'benkoenig',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    email: 'chloe@example.com',
    name: 'Chloe Svoboda',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    bio: 'New in town, looking for games!',
    karmaPoints: 15,
    skillLevels: { handball: 'intermediate', 'water-polo': 'beginner' },
    notificationPreferences: { handball: true, 'water-polo': true },
    preferredCurrency: 'CZK',
    location: 'Prague, Czech Republic',
    createdAt: new Date('2024-02-15'),
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Sunday Football at Letná Park',
    description: 'Friendly match with good vibes. All levels welcome!',
    sport: 'football',
    venueId: '1', // Letná Park Football Field
    date: new Date('2024-12-15'),
    startTime: '18:00',
    duration: 90,
    minParticipants: 8,
    idealParticipants: 12,
    maxParticipants: 14,
    cancellationDeadlineHours: 2,
    price: 15,
    paymentDetails: 'Revolut: @alexnovak or cash on spot',
    gameRules: 'No slide tackles, bring light/dark shirt, fair play',
    cutoffTime: new Date('2024-12-15T16:00:00'),
    isPublic: true,
    organizerId: '1',
    participants: ['1', '2', '3'],
    waitlist: [],
    status: 'open',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: '2',
    title: 'Morning Basketball',
    description: 'Quick game before work starts',
    sport: 'basketball',
    venueId: '3', // Wenceslas Square Basketball Court
    date: new Date('2024-12-16'),
    startTime: '07:30',
    duration: 60,
    minParticipants: 6,
    idealParticipants: 8,
    maxParticipants: 10,
    cancellationDeadlineHours: 1,
    price: 8,
    cutoffTime: new Date('2024-12-16T06:30:00'),
    isPublic: true,
    organizerId: '2',
    participants: ['2', '3'],
    waitlist: [],
    status: 'open',
    createdAt: new Date('2024-12-11'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '3',
    title: 'Handball Training Session',
    description: 'Improve your handball skills with experienced players',
    sport: 'handball',
    venueId: '2', // Karlín Sports Hall
    date: new Date('2024-12-17'),
    startTime: '19:00',
    duration: 120,
    minParticipants: 10,
    idealParticipants: 14,
    maxParticipants: 16,
    cancellationDeadlineHours: 3,
    price: 12,
    cutoffTime: new Date('2024-12-17T17:00:00'),
    isPublic: true,
    organizerId: '3',
    participants: ['3'],
    waitlist: [],
    status: 'open',
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: '4',
    title: 'Ice Hockey Pick-up Game',
    description: 'Casual ice hockey game, all skill levels welcome',
    sport: 'ice-hockey',
    venueId: '4', // Winter Stadium Štvanice
    date: new Date('2024-12-18'),
    startTime: '20:30',
    duration: 90,
    minParticipants: 12,
    idealParticipants: 16,
    maxParticipants: 20,
    cancellationDeadlineHours: 4,
    price: 25,
    paymentDetails: 'Ice time rental split between players',
    cutoffTime: new Date('2024-12-18T18:00:00'),
    isPublic: true,
    organizerId: '1',
    participants: ['1', '2'],
    waitlist: [],
    status: 'open',
    createdAt: new Date('2024-12-13'),
    updatedAt: new Date('2024-12-13'),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'event_joined',
    title: 'New Player Joined',
    message: 'Chloe Svoboda joined your event "Sunday Football at Letná Park"',
    eventId: '1',
    fromUserId: '3',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: '2',
    userId: '1',
    type: 'event_confirmed',
    title: 'Event Confirmed',
    message: 'Your event "Sunday Football at Letná Park" has reached minimum participants and is confirmed!',
    eventId: '1',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
  },
  {
    id: '3',
    userId: '1',
    type: 'karma_received',
    title: 'Karma Received',
    message: 'You received +5 karma points from Ben König for great sportsmanship',
    fromUserId: '2',
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    id: '4',
    userId: '1',
    type: 'event_reminder',
    title: 'Event Reminder',
    message: 'Your event "Sunday Football at Letná Park" starts in 2 hours',
    eventId: '1',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    id: '5',
    userId: '1',
    type: 'payment_received',
    title: 'Payment Received',
    message: 'Ben König paid €15 for "Sunday Football at Letná Park"',
    eventId: '1',
    fromUserId: '2',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
  },
  {
    id: '6',
    userId: '1',
    type: 'moved_from_waitlist',
    title: 'Moved from Waitlist',
    message: 'You\'ve been moved from waitlist to confirmed for "Ice Hockey Pick-up Game"',
    eventId: '4',
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
  },
];

// Export venues for backward compatibility
export { mockVenues };