/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileRouteImport } from './routes/user-profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManageVenuesRouteImport } from './routes/manage-venues'
import { Route as ManageCoreGroupsRouteImport } from './routes/manage-core-groups'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EditEventEventIdRouteImport } from './routes/edit-event.$eventId'
import { Route as CitiesCitySlugRouteImport } from './routes/cities/$citySlug'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as CitySlugSportSlugRouteImport } from './routes/$citySlug/$sportSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgEventEventIdRouteImport } from './routes/api/og/event/$eventId'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageVenuesRoute = ManageVenuesRouteImport.update({
  id: '/manage-venues',
  path: '/manage-venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCoreGroupsRoute = ManageCoreGroupsRouteImport.update({
  id: '/manage-core-groups',
  path: '/manage-core-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEventEventIdRoute = EditEventEventIdRouteImport.update({
  id: '/edit-event/$eventId',
  path: '/edit-event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCitySlugRoute = CitiesCitySlugRouteImport.update({
  id: '/cities/$citySlug',
  path: '/cities/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugSportSlugRoute = CitySlugSportSlugRouteImport.update({
  id: '/$citySlug/$sportSlug',
  path: '/$citySlug/$sportSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgEventEventIdRoute = ApiOgEventEventIdRouteImport.update({
  id: '/api/og/event/$eventId',
  path: '/api/og/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manage-core-groups': typeof ManageCoreGroupsRoute
  '/manage-venues': typeof ManageVenuesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/user-profile': typeof UserProfileRoute
  '/$citySlug/$sportSlug': typeof CitySlugSportSlugRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/edit-event/$eventId': typeof EditEventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manage-core-groups': typeof ManageCoreGroupsRoute
  '/manage-venues': typeof ManageVenuesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/user-profile': typeof UserProfileRoute
  '/$citySlug/$sportSlug': typeof CitySlugSportSlugRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/edit-event/$eventId': typeof EditEventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/manage-core-groups': typeof ManageCoreGroupsRoute
  '/manage-venues': typeof ManageVenuesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/user-profile': typeof UserProfileRoute
  '/$citySlug/$sportSlug': typeof CitySlugSportSlugRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/edit-event/$eventId': typeof EditEventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/event/$eventId': typeof ApiOgEventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/discover'
    | '/leaderboard'
    | '/manage-core-groups'
    | '/manage-venues'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/user-profile'
    | '/$citySlug/$sportSlug'
    | '/auth/$pathname'
    | '/cities/$citySlug'
    | '/edit-event/$eventId'
    | '/events/$eventId'
    | '/api/auth/$'
    | '/api/og/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/discover'
    | '/leaderboard'
    | '/manage-core-groups'
    | '/manage-venues'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/user-profile'
    | '/$citySlug/$sportSlug'
    | '/auth/$pathname'
    | '/cities/$citySlug'
    | '/edit-event/$eventId'
    | '/events/$eventId'
    | '/api/auth/$'
    | '/api/og/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/discover'
    | '/leaderboard'
    | '/manage-core-groups'
    | '/manage-venues'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/user-profile'
    | '/$citySlug/$sportSlug'
    | '/auth/$pathname'
    | '/cities/$citySlug'
    | '/edit-event/$eventId'
    | '/events/$eventId'
    | '/api/auth/$'
    | '/api/og/event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ManageCoreGroupsRoute: typeof ManageCoreGroupsRoute
  ManageVenuesRoute: typeof ManageVenuesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UserProfileRoute: typeof UserProfileRoute
  CitySlugSportSlugRoute: typeof CitySlugSportSlugRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  CitiesCitySlugRoute: typeof CitiesCitySlugRoute
  EditEventEventIdRoute: typeof EditEventEventIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgEventEventIdRoute: typeof ApiOgEventEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile': {
      id: '/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-venues': {
      id: '/manage-venues'
      path: '/manage-venues'
      fullPath: '/manage-venues'
      preLoaderRoute: typeof ManageVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-core-groups': {
      id: '/manage-core-groups'
      path: '/manage-core-groups'
      fullPath: '/manage-core-groups'
      preLoaderRoute: typeof ManageCoreGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-event/$eventId': {
      id: '/edit-event/$eventId'
      path: '/edit-event/$eventId'
      fullPath: '/edit-event/$eventId'
      preLoaderRoute: typeof EditEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$citySlug': {
      id: '/cities/$citySlug'
      path: '/cities/$citySlug'
      fullPath: '/cities/$citySlug'
      preLoaderRoute: typeof CitiesCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/$sportSlug': {
      id: '/$citySlug/$sportSlug'
      path: '/$citySlug/$sportSlug'
      fullPath: '/$citySlug/$sportSlug'
      preLoaderRoute: typeof CitySlugSportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/event/$eventId': {
      id: '/api/og/event/$eventId'
      path: '/api/og/event/$eventId'
      fullPath: '/api/og/event/$eventId'
      preLoaderRoute: typeof ApiOgEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  LeaderboardRoute: LeaderboardRoute,
  ManageCoreGroupsRoute: ManageCoreGroupsRoute,
  ManageVenuesRoute: ManageVenuesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UserProfileRoute: UserProfileRoute,
  CitySlugSportSlugRoute: CitySlugSportSlugRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  CitiesCitySlugRoute: CitiesCitySlugRoute,
  EditEventEventIdRoute: EditEventEventIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgEventEventIdRoute: ApiOgEventEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
