name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - web-app/**/*.ts'
      - web-app/**/*.tsx'
      - web-app/wrangler.*'
      - web-app/pnpm-*.yaml'
      - web-app/.github/workflows/deploy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build app
        working-directory: web-app
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: |
          pnpm run lingui:extract

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        working-directory: web-app
        env:
          TURSO_DATABASE_URL: ${{ vars.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
					RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

        with:
          packageManager: pnpm
          secrets: |
            TURSO_AUTH_TOKEN
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
            GOOGLE_CLIENT_SECRET
            GOOGLE_CLIENT_ID
            FACEBOOK_CLIENT_SECRET
            FACEBOOK_CLIENT_ID
            RESEND_API_KEY
          vars: |
            TURSO_DATABASE_URL

          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
