import type { AuthLocalization } from '@daveyplate/better-auth-ui'
import { msg } from '@lingui/core/macro'
import { i18n } from './i18n'

const authMessages = {
  ALREADY_HAVE_AN_ACCOUNT: msg`Already have an account?`,
  AVATAR: msg`Avatar`,
  BACKUP_CODE: msg`Backup Code`,
  BACKUP_CODE_PLACEHOLDER: msg`Backup Code`,
  BACKUP_CODE_REQUIRED: msg`Backup code is required`,
  CANCEL: msg`Cancel`,
  CONFIRM_PASSWORD: msg`Confirm Password`,
  CONFIRM_PASSWORD_PLACEHOLDER: msg`Confirm Password`,
  CONFIRM_PASSWORD_REQUIRED: msg`Confirm password is required`,
  CONTINUE_WITH_AUTHENTICATOR: msg`Continue with Authenticator`,
  DELETE_AVATAR: msg`Delete Avatar`,
  DISABLED_CREDENTIALS_DESCRIPTION: msg`Choose a provider to login to your account`,
  DONT_HAVE_AN_ACCOUNT: msg`Don't have an account?`,
  EMAIL: msg`Email`,
  EMAIL_OTP: msg`Email Code`,
  EMAIL_OTP_SEND_ACTION: msg`Send code`,
  EMAIL_OTP_VERIFICATION_SENT: msg`Please check your email for the verification code.`,
  EMAIL_OTP_VERIFY_ACTION: msg`Verify code`,
  EMAIL_PLACEHOLDER: msg`m@example.com`,
  EMAIL_REQUIRED: msg`Email address is required`,
  EMAIL_VERIFICATION: msg`Email Verification`,
  EMAIL_VERIFICATION_DESCRIPTION: msg`Please check your email for the verification code to complete your registration.`,
  EMAIL_VERIFICATION_SUCCESS: msg`Email verification successful.`,
  FORGOT_AUTHENTICATOR: msg`Forgot authenticator?`,
  FORGOT_PASSWORD: msg`Forgot Password`,
  FORGOT_PASSWORD_ACTION: msg`Send reset link`,
  FORGOT_PASSWORD_DESCRIPTION: msg`Enter your email to reset your password`,
  FORGOT_PASSWORD_EMAIL: msg`Check your email for the password reset link.`,
  FORGOT_PASSWORD_LINK: msg`Forgot your password?`,
  GO_BACK: msg`Go back`,
  IS_INVALID: msg`is invalid`,
  IS_REQUIRED: msg`is required`,
  MAGIC_LINK: msg`Magic Link`,
  MAGIC_LINK_ACTION: msg`Send magic link`,
  MAGIC_LINK_DESCRIPTION: msg`Enter your email to receive a magic link`,
  MAGIC_LINK_EMAIL: msg`Check your email for the magic link`,
  NAME: msg`Name`,
  NAME_PLACEHOLDER: msg`Name`,
  NEW_PASSWORD: msg`New Password`,
  NEW_PASSWORD_PLACEHOLDER: msg`New Password`,
  NEW_PASSWORD_REQUIRED: msg`New password is required`,
  ONE_TIME_PASSWORD: msg`One-Time Password`,
  OPTIONAL_BRACKETS: msg`(Optional)`,
  OR_CONTINUE_WITH: msg`Or continue with`,
  PASSWORD: msg`Password`,
  PASSWORDS_DO_NOT_MATCH: msg`Passwords do not match`,
  PASSWORD_PLACEHOLDER: msg`Password`,
  PASSWORD_REQUIRED: msg`Password is required`,
  RECOVER_ACCOUNT: msg`Recover Account`,
  RECOVER_ACCOUNT_DESCRIPTION: msg`Please enter a backup code to access your account`,
  RECOVER_ACCOUNT_ACTION: msg`Recover account`,
  REMEMBER_ME: msg`Remember me`,
  RESEND_CODE: msg`Resend code`,
  RESEND_VERIFICATION_EMAIL: msg`Resend Verification Email`,
  RESET_PASSWORD: msg`Reset Password`,
  RESET_PASSWORD_ACTION: msg`Save new password`,
  RESET_PASSWORD_DESCRIPTION: msg`Enter your new password below`,
  RESET_PASSWORD_SUCCESS: msg`Password reset successfully`,
  REQUEST_FAILED: msg`Request failed`,
  SEND_VERIFICATION_CODE: msg`Send verification code`,
  SIGN_IN: msg`Sign In`,
  SIGN_IN_ACTION: msg`Login`,
  SIGN_IN_DESCRIPTION: msg`Enter your email below to login to your account`,
  SIGN_IN_USERNAME_DESCRIPTION: msg`Enter your username or email to login to your account`,
  SIGN_IN_USERNAME_PLACEHOLDER: msg`Username or email`,
  SIGN_IN_WITH: msg`Sign in with`,
  SIGN_OUT: msg`Sign Out`,
  SIGN_UP: msg`Sign Up`,
  SIGN_UP_ACTION: msg`Create an account`,
  SIGN_UP_DESCRIPTION: msg`Enter your information to create an account`,
  SIGN_UP_EMAIL: msg`Check your email for the verification link.`,
  TRUST_DEVICE: msg`Trust this device`,
  TWO_FACTOR: msg`Two-Factor`,
  TWO_FACTOR_ACTION: msg`Verify code`,
  TWO_FACTOR_DESCRIPTION: msg`Please enter your one-time password to continue`,
  TWO_FACTOR_TOTP_LABEL: msg`Scan the QR Code with your Authenticator`,
  UPLOAD: msg`Upload`,
  UPLOAD_AVATAR: msg`Upload Avatar`,
  USERNAME: msg`Username`,
  USERNAME_PLACEHOLDER: msg`Username`,
  VERIFY_YOUR_EMAIL: msg`Verify Your Email`,
  VERIFY_YOUR_EMAIL_DESCRIPTION: msg`Please verify your email address. Check your inbox for the verification email. If you haven't received the email, click the button below to resend.`,
  SESSION_NOT_FRESH: msg`Your session is not fresh. Please sign in again.`,
  USER_NOT_FOUND: msg`User not found`,
  FAILED_TO_CREATE_USER: msg`Failed to create user`,
  FAILED_TO_CREATE_SESSION: msg`Failed to create session`,
  FAILED_TO_UPDATE_USER: msg`Failed to update user`,
  FAILED_TO_GET_SESSION: msg`Failed to get session`,
  INVALID_PASSWORD: msg`Invalid password`,
  INVALID_EMAIL: msg`Invalid email`,
  INVALID_EMAIL_OR_PASSWORD: msg`Invalid email or password`,
  SOCIAL_ACCOUNT_ALREADY_LINKED: msg`Social account already linked`,
  PROVIDER_NOT_FOUND: msg`Provider not found`,
  INVALID_TOKEN: msg`Invalid token`,
  ID_TOKEN_NOT_SUPPORTED: msg`id_token not supported`,
  FAILED_TO_GET_USER_INFO: msg`Failed to get user info`,
  USER_EMAIL_NOT_FOUND: msg`User email not found`,
  EMAIL_NOT_VERIFIED: msg`Email not verified`,
  PASSWORD_TOO_SHORT: msg`Password too short`,
  PASSWORD_TOO_LONG: msg`Password too long`,
  USER_ALREADY_EXISTS: msg`User already exists`,
  EMAIL_CAN_NOT_BE_UPDATED: msg`Email can not be updated`,
  CREDENTIAL_ACCOUNT_NOT_FOUND: msg`Credential account not found`,
  SESSION_EXPIRED: msg`Session expired. Re-authenticate to perform this action.`,
  FAILED_TO_UNLINK_LAST_ACCOUNT: msg`You can't unlink your last account`,
  ACCOUNT_NOT_FOUND: msg`Account not found`,
  USER_ALREADY_HAS_PASSWORD: msg`User already has a password. Provide that to delete the account.`,
} as const

export function getAuthLocalization(): AuthLocalization {
  return Object.fromEntries(
    Object.entries(authMessages).map(([key, message]) => [key, i18n._(message)])
  )
}
